const projectData = [
  {
    git: "https://github.com/metzo32/arto",
    deployed: true,
    url: "https://arto-33hwth26j-metzs-projects-579177d6.vercel.app/",
    thumbnail: "/videos/video_arto.gif",
    title: "Arto",
    description: "아티스트 포트폴리오 서칭 서비스",
    text: "App router 기반의 Next.js를 활용하여 작가의 전시 이력, 주요 포트폴리오 및 작업 방향을 살펴볼 수 있는 서비스입니다. Firebase를 기반으로 사용자 인증 및 좋아요 기능을 구현하였습니다. 쿼리 스트링을 활용하여 동적 페이지를 생성하는 방식으로 검색 페이지를 완성했습니다.",
    skills: [
      "Next.js",
      "Typescript",
      "Zustand",
      "Styled-Components",
      "Firebase",
    ],
  },
  {
    git: "https://github.com/metzo32/plantic",
    deployed: false,
    url: "https://github.com/metzo32/plantic",
    thumbnail: "/videos/video_plantic.webp",
    title: "Plantic",
    description: "실내 식물 정보 검색 서비스",
    text: "공공 데이터 API를 활용한 실내 식물 검색 서비스입니다. 한글 및 영문 이름의 검색이 가능하고, 난이도를 비롯한 광도, 습도, 성장 속도에 따라 아이콘이 부여될 수 있도록 구현했습니다.",
    skills: [
      "Typescript",
      "React",
      "Redux",
      "Tailwind",
      "React-Router-DOM",
      "Vite",
    ],
  },
  {
    git: "https://github.com/metzo32/tapttoo_gen",
    deployed: true,
    url: "https://tapttoo.netlify.app/",
    thumbnail: "/videos/video_tapttoo.webp",
    title: "Tapttoo",
    description: "커스텀 타투 도안 제작 서비스",
    text: "DALL-E API를 활용하여 유저가 작성한 프롬프트에 따라 타투 이미지를 생성해주는 서비스입니다.",
    skills: [
      "Typescript",
      "React",
      "Styled-Components",
      "React-Router-DOM",
      "Axios",
    ],
  },
  {
    git: "https://github.com/metzo32/keyboard",
    deployed: true,
    url: "https://checkkeyboardsound.netlify.app/",
    thumbnail: "/videos/video_keyboard.webp",
    title: "가상 키보드",
    description: "키보드 타건음 체크 서비스",
    text: "키보드를 고를 때 타건음이 녹음 환경마다 다르다는 점을 개선하고자 웹 상에서 키보드를 테스트해 볼 수 있도록 했습니다. 실제 키와 매핑하여 타이핑이 가능하고, 각 키마다 오디오 객체를 활용하여 소리를 체크할 수 있습니다.",
    skills: ["Typescript", "React", "Tailwind"],
  },
  {
    git: "https://github.com/metzo32/mbtitest_ts",
    deployed: true,
    url: "https://discordpizza.netlify.app/",
    thumbnail: "/videos/video_pizza.webp",
    title: "나는 어떤 피자일까?",
    description: "나의 MBTI와 어울리는 피자를 알려주는 테스트",
    text: "MBTI 테스트 로직을 바탕으로 디스코드 친구들의 일화를 적용한 심리 테스트입니다.",
    skills: [
      "Typescript",
      "React",
      "React-Router-DOM",
      "Styled-Components",
      "Bootstrap",
    ],
  },
  {
    git: "https://github.com/metzo32/numberGame",
    deployed: false,
    url: "https://github.com/metzo32/numberGame",
    thumbnail: "/videos/video_numbergame.webp",
    title: "숫자 업다운 게임",
    description: "입력한 숫자를 프로그램이 맞춰나가는 게임",
    text: "유저가 입력한 수를 업다운 방식으로 프로그램이 추측할 수 있도록 구현했습니다.",
    skills: ["React-Native", "ngrok"],
  },
  // {
  //   git: "",
  //   deployed: false,
  //   url: "",
  //   thumbnail: "",
  //   title: "Todo List",
  //   description: "프로젝트 설명",
  //   text: "더 자세한 설명",
  //   skills: ["React-Native"],
  // },
  {
    git: "https://github.com/metzo32/next_bookstore_approuter",
    deployed: false,
    url: "https://github.com/metzo32/next_bookstore_approuter",
    thumbnail: "",
    title: "도서 목록 검색",
    description: "Next.js의 Page Router와 App Router 버전 실습",
    text: "제공된 백엔드 데이터를 불러와 SSR, ISR을 비롯해 인터셉트 라우팅, 스켈레톤 UI 등 대표적인 기능을 사용해 기초를 다졌습니다.",
    skills: ["Typescript", "Next.js"],
  },
];

export default projectData;
